INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (1,'Sin especialidad',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (2,'Alergia e Inmunología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (3,'Anatomía Patológica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (4,'Anestesología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (5,'Anestesología Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (6,'Angiología y Cirugía Vascular',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (7,'Calidad de la Atención Clínica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (8,'Cardiología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (9,'Cirugía Avanzada de Columna Vertebral',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (10,'Cirugía Bariátrica y Metabólica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (11,'Cirugía Cardiotorácica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (12,'Cirugía de Trauma Toraco-Abdominal',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (13,'Cirugía General',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (14,'Cirugía Laparoscópica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (15,'Cirugía Oncológic',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (16,'Cirugía Oncológica de Cabeza y Cuello',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (17,'Cirugía Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (18,'Cirugía Plástica y Reconstructiva',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (19,'Coloproctología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (20,'Dermatología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (21,'Dermatología Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (22,'Endocrinología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (23,'Endoscopía Ginecológica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (24,'Epidemiología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (25,'Gastroenterología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (26,'Gastroenterología Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (27,'Genética Médica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (28,'Geriatría',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (29,'Ginecología Obstetrici',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (30,'Ginecología Oncológica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (31,'Hematología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (32,'Hemodinamia Cardiología Intervencionista',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (33,'Infectología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (34,'Infectología Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (35,'Medicina de Rehabilitación',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (36,'Medicina del Enfermo en Estado Crítico',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (37,'Medicina del Trabajo y Ambiental',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (38,'Medicina Familiar',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (39,'Medicina Integrada',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (40,'Medicina Interna',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (41,'Medicina Materno Fetal',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (42,'Medicina Paliativa y del Dolor',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (43,'Nefrología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (44,'Neonatología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (45,'Neumología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (46,'Neurocirugía',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (47,'Neurología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (48,'Oftalmología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (49,'Oncología Hematología Pediátrica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (50,'Oncología Médica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (51,'Otorrinolaringología y Cirugía de Cabeza y Cuello',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (52,'Psiquiatría',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (53,'Patología Clínica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (54,'Pediatría Médica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (55,'Radiología e Imagen',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (56,'Radio-Oncología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (57,'Retina Médica y Quirúrgica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (58,'Reumatología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (59,'Traumatología y Ortopedia',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (60,'Urología',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (61,'Urgencias Médica',1,null);
INSERT INTO Esp_Medicas(idEsp_Medicas,NombreEsp_Medica,Status,Descripcion) VALUES (62,'Urología Ginecológica',1,null);
commit

